#projectName=OpenCart
#projectName=Amazon
projectName=Swag Labs
#projectName=Test Automation Website
#projectName=Instax
#projectName=OrangeHRM

browser = chrome
#url = https://tutorialsninja.com/demo/
#url = https://www.amazon.in/
#url=https://www.saucedemo.com/
url=https://www.saucedemo.com/inventory.html
#url=https://testautomationpractice.blogspot.com/
#url=https://www.instax.in/
#url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

#Sauce Labs
#username=demo5231@gmail.com
#password=demo5231
#username=visual_user
username=standard_user
password=secret_sauce
#username=Admin
#password=admin123

#OrangeHRM
#username=Admin
#password=admin123

Login=true

excelFileName=swagLabsData.xlsx
sheetName=Login

headless = false